trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

variables:
- name: vmImageName
  value: 'ubuntu-latest'
- name: WebAppName
  value: 'digitalchuck'
- name: azureSubscription
  value: 'AzDo'
- name: ResourceGroupName
  value: 'sg-digitalchuck'
- name: buildConfiguration
  value: 'Release'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build and Publish Chuck
    workspace:
      clean: all
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        noCache: false
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
        workingDirectory: $(Agent.BuildDirectory)/src
      displayName: 'dotnet build $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
        workingDirectory: $(Agent.BuildDirectory)/src

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '$(WebAppName)'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy WebApp: $(WebAppName)'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webApp'
        WebAppName: $(WebAppName)
        ResourceGroupName: $(ResourceGroupName)
        deployToSlotOrASE: false
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        enableXmlTransform: false
