trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

variables:
- name: vmImageName
  value: 'windows-2022'
- name: workingDirectory
  value: '/'
- name: WebAppName
  value: 'webapp-gallows'
- name: azureSubscription
  value: 'AzDo'
- name: appName
  value: 'Chuck-Dotnet'
- name: ResourceGroupName
  value: 'rg-webapp'
- name: buildArgs
  value: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: all

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        noCache: false
    
    - task: VSBuild@1
      displayName: 'VSBuild: Chuck'
      inputs:
        solution: '**/chuck-dotnet.csproj'
        msbuildArgs: $(buildArgs)
        platform: 'AnyCPU'
        configuration: 'Release'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish: Build Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: drop

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy WebApp: $(appName)'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webApp'
        WebAppName: $(WebAppName)
        ResourceGroupName: $(ResourceGroupName)
        deployToSlotOrASE: false
        package: '$(Build.ArtifactStagingDirectory)\**\chuck-dotnet.zip'
        enableXmlTransform: false