trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

variables:
- name: vmImageName
  value: 'ubuntu-latest'
- name: workingDirectory
  value: '/'
- name: WebAppName
  value: 'webapp-gallows'
- name: azureSubscription
  value: 'AzDo'
- name: appName
  value: 'Chuck-Dotnet'
- name: ResourceGroupName
  value: 'rg-webapp'
- name: buildConfiguration
  value: 'Release'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: all

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        noCache: false
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
      displayName: 'dotnet build $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '$(appName)'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy WebApp: $(appName)'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webApp'
        WebAppName: $(WebAppName)
        ResourceGroupName: $(ResourceGroupName)
        deployToSlotOrASE: false
        package: '$(Build.ArtifactStagingDirectory)\**\*.zip'
        enableXmlTransform: false